name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install dependencies
      run: dotnet restore ./Advent-of-Code-2020/Advent-of-Code-2020.sln
    - name: Build
      run: dotnet build ./Advent-of-Code-2020/Advent-of-Code-2020.sln --no-restore
      
